# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 孙康博的个人博客 Blog of SUN Kangbo
email: kangbosun67167@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  本博客用于个人搬砖过程中的个人想法梳理，同时锻炼写作能力，使用中英文两种语言描述。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://myblog.dogson.cn" # the base hostname & protocol for your site
twitter_username: KangboSun1996
github_username:  kangbosun67167

# Build settings
markdown: kramdown
